name       : perl-devel-symdump
version    : 2.18
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/A/AN/ANDK/Devel-Symdump-2.18.tar.gz : 826f81a107f5592a2516766ed43beb47e10cc83edc9ea48090b02a36040776c0
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Devel::Symdump - dump symbol names or the symbol table
description: |
    Devel::Symdump - dump symbol names or the symbol table
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
